language: smalltalk

smalltalk:
  - Squeak-4.6

env:
  global:
    - BASELINE=Algernon
    - PACKAGES="/packages"

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386