name: smalltalkCI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hpi-swa/setup-smalltalkCI@v1
      id: smalltalkci
      with:
        smalltalk-version: 'Squeak64-trunk'
    - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
      timeout-minutes: 15
